const $=id=>document.getElementById(id);
let frames=[],options=['',''],lastResult=null,lastInput=null,uploading=false,running=false,videoURL=null,revision=0;
const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const initialModel=new URLSearchParams(location.search).get('model');if(['qwen4b','gemma-e4b','gemma-e2b','minicpm-v45','internvl35-8b','internvl35-14b'].includes(initialModel))$('model-select').value=initialModel;
function error(message){$('error').textContent=message;$('error').hidden=!message;}
function changed(){revision++;if(lastResult)$('stale-result').hidden=false;}
function lockSubmit(){$('submit').disabled=running||uploading;}
function renderOptions(){const root=$('options');root.replaceChildren();options.forEach((value,i)=>{const row=document.createElement('div');row.className='option-row';const label=document.createElement('label');label.className='option-letter';label.textContent=letters[i];label.htmlFor='option-'+i;const input=document.createElement('textarea');input.id='option-'+i;input.rows=1;input.maxLength=4000;input.required=true;input.value=value;input.placeholder='填写选项 '+letters[i]+' 的内容';input.addEventListener('input',()=>{options[i]=input.value;changed();});const remove=document.createElement('button');remove.type='button';remove.className='remove-option';remove.textContent='×';remove.title='删除选项 '+letters[i];remove.setAttribute('aria-label',remove.title);remove.disabled=options.length<=2;remove.onclick=()=>{options.splice(i,1);renderOptions();changed();};row.append(label,input,remove);root.append(row);});$('option-count').textContent=options.length+' / 26';$('add-option').disabled=options.length>=26;}
$('add-option').onclick=()=>{options.push('');renderOptions();changed();$('option-'+(options.length-1)).focus();};
function renderFrames(){const root=$('media-previews'),meta=$('frame-metadata');root.replaceChildren();meta.replaceChildren();frames.forEach((f,i)=>{const preview=document.createElement('div');preview.className='preview';const img=document.createElement('img');img.src='data:'+(f.mime||'image/jpeg')+';base64,'+f.base64;img.alt=f.name;const caption=document.createElement('small');caption.textContent=f.name;caption.title=f.name;const remove=document.createElement('button');remove.type='button';remove.className='remove-media';remove.textContent='×';remove.title='删除 '+f.name;remove.setAttribute('aria-label',remove.title);remove.onclick=()=>{frames.splice(i,1);renderFrames();changed();};preview.append(img,remove,caption);root.append(preview);const row=document.createElement('div');row.className='metadata-row';const title=document.createElement('span');title.textContent='帧 '+(i+1);row.append(title);for(const [key,label,type] of [['camera_id','相机标识','text'],['timestamp_ms','时间戳（毫秒）','number']]){const wrap=document.createElement('label');wrap.textContent=label;const input=document.createElement('input');input.type=type;input.value=f[key];input.addEventListener('input',()=>{f[key]=type==='number'?Number(input.value):input.value;changed();});wrap.append(input);row.append(wrap);}meta.append(row);});$('frame-count').textContent=frames.length+' / 8 帧';}
async function api(path,config){let r;try{r=await fetch(path,config);}catch(e){throw new Error('网络连接失败，请检查连接后重试。');}let data;try{data=await r.json();}catch(e){throw new Error('服务没有返回有效数据，请稍后重试。');}if(!r.ok){const message=typeof data.detail==='string'?data.detail:JSON.stringify(data.detail);throw new Error(message||'请求失败');}return data;}
async function upload(files,kind){if(uploading||running)return;error('');if(kind==='image'&&files.length+frames.length>8){error('图片和视频帧合计最多8张，请先删除部分观察。');return;}const count=Number($('video-count').value);if(kind==='video'&&count+frames.length>8){error('新增视频帧将超过8张，请减少抽帧数或删除已有观察。');return;}uploading=true;lockSubmit();try{for(let i=0;i<files.length;i++){const file=files[i];$('upload-status').textContent=kind==='video'?'正在解码视频并抽取画面…':'正在上传 '+(i+1)+' / '+files.length+'…';const form=new FormData();form.append('file',file);form.append('kind',kind);if(kind==='video'){form.append('start',$('video-start').value||'0');form.append('end',$('video-end').value);form.append('count',count);}const data=await api('/api/media',{method:'POST',body:form});frames.push(...data.frames);renderFrames();changed();if(kind==='video'){if(videoURL)URL.revokeObjectURL(videoURL);videoURL=URL.createObjectURL(file);$('video-preview').src=videoURL;$('video-preview').hidden=false;}}$('upload-status').textContent='已添加 '+frames.length+' 帧观察';}catch(e){error(e.message);$('upload-status').textContent='';}finally{uploading=false;lockSubmit();$('image-file').value='';$('video-file').value='';}}
$('image-file').onchange=e=>upload([...e.target.files],'image');$('video-file').onchange=e=>upload([...e.target.files],'video');
for(const name of ['dragenter','dragover'])$('dropzone').addEventListener(name,e=>{e.preventDefault();$('dropzone').classList.add('dragover');});for(const name of ['dragleave','drop'])$('dropzone').addEventListener(name,e=>{e.preventDefault();$('dropzone').classList.remove('dragover');if(name==='drop')upload([...e.dataTransfer.files],'image');});
function tab(video){$('video-controls').hidden=!video;$('image-controls').hidden=video;$('video-tab').classList.toggle('active',video);$('image-tab').classList.toggle('active',!video);}
$('image-tab').onclick=()=>tab(false);$('video-tab').onclick=()=>tab(true);
for(const id of ['question','state-text','state-json'])$(id).addEventListener('input',changed);
$('show-fields').onclick=()=>{$('state-fields').hidden=!$('state-fields').hidden;};
function showResult(result){lastResult=result;$('empty-result').hidden=true;$('actual-result').hidden=false;$('stale-result').hidden=true;$('winner-id').textContent=result.answer;$('winner-text').textContent=result.answer_text;$('winner-prob').textContent=(result.distribution[result.answer]*100).toFixed(2)+'%';$('bars').replaceChildren();Object.entries(result.distribution).forEach(([id,p])=>{const row=document.createElement('div');row.className='bar-row'+(id===result.answer?' winner':'');const caption=document.createElement('div');caption.className='bar-caption';const text=document.createElement('span');const letter=document.createElement('b');letter.textContent=id;text.append(letter,document.createTextNode(result.options[id]));const percent=document.createElement('span');percent.className='percent';percent.textContent=(p*100).toFixed(2)+'%';caption.append(text,percent);const track=document.createElement('div');track.className='bar-track';track.setAttribute('role','meter');track.setAttribute('aria-label','选项 '+id+' 的概率');track.setAttribute('aria-valuemin','0');track.setAttribute('aria-valuemax','100');track.setAttribute('aria-valuenow',(p*100).toFixed(2));const fill=document.createElement('div');fill.className='bar-fill';track.append(fill);row.append(caption,track);$('bars').append(row);requestAnimationFrame(()=>requestAnimationFrame(()=>fill.style.width=(p*100)+'%'));});$('result-meta').replaceChildren();for(const value of [result.model,'耗时 '+(result.latency_ms/1000).toFixed(2)+'s',result.image_count+' 帧观察',result.input_tokens+' 输入token']){const span=document.createElement('span');span.textContent=value;$('result-meta').append(span);}}
$('decision-form').onsubmit=async e=>{e.preventDefault();if(running||uploading)return;error('');let state={};try{state=$('state-json').value.trim()?JSON.parse($('state-json').value):{};if(!state||Array.isArray(state)||typeof state!=='object')throw new Error();}catch(e){error('结构化状态必须是有效的JSON对象。');return;}const payload={model_id:$('model-select').value,question:$('question').value,state_text:$('state-text').value,state_json:state,options:options.map((text,i)=>({id:letters[i],text})),images:frames.map(({base64,timestamp_ms,camera_id})=>({base64,timestamp_ms,camera_id,modality:'rgb'}))};if(payload.images.some(f=>!Number.isFinite(f.timestamp_ms))){error('帧时间戳必须是有限数值。');return;}const submittedRevision=revision;const snapshot={...payload,images:frames.map(({name,timestamp_ms,camera_id,width,height})=>({name,timestamp_ms,camera_id,width,height}))};running=true;lockSubmit();$('empty-result').hidden=true;$('actual-result').hidden=true;$('loading-result').hidden=false;try{const result=await api('/api/decide',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});lastInput=snapshot;showResult(result);$('stale-result').hidden=submittedRevision===revision;if(window.innerWidth<760)$('actual-result').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){error(e.message);$('actual-result').hidden=!lastResult;$('empty-result').hidden=!!lastResult;}finally{running=false;$('loading-result').hidden=true;lockSubmit();}};
$('export-result').onclick=()=>{if(!lastResult)return;const blob=new Blob([JSON.stringify({input:lastInput,result:lastResult,exported_at:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='multimodal-decision-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);};
function clear(){if(running||uploading)return;$('question').value='';$('state-text').value='';$('state-json').value='';frames=[];options=['',''];lastResult=null;lastInput=null;renderOptions();renderFrames();$('actual-result').hidden=true;$('empty-result').hidden=false;$('video-preview').hidden=true;if(videoURL){URL.revokeObjectURL(videoURL);videoURL=null;}$('upload-status').textContent='';error('');}
$('clear').onclick=clear;$('example').onclick=()=>{if(running||uploading)return;clear();$('question').value='根据状态，接下来应该采用哪种处理方式？';$('state-text').value='正在检查一份扫描文档。关键字段的文字较小，当前图像清晰，但还没有读取到所需内容。目标是准确提取这个字段。';options=['放大关键字段区域后再读取','跳过文档并猜测字段内容','直接认定字段不存在'];renderOptions();};
async function health(){try{const data=await api('/api/health?model_id='+encodeURIComponent($('model-select').value));$('connection').classList.toggle('ready',data.model_ready);$('connection').querySelector('span').textContent=data.model_ready?(data.busy?'模型处理中':(data.loaded?'模型已连接':'模型就绪 · 首次提交会加载')):'模型下载中或服务尚未就绪';}catch(e){$('connection').classList.remove('ready');$('connection').querySelector('span').textContent='连接暂时中断';}}
renderOptions();renderFrames();health();setInterval(health,15000);api('/api/capabilities').then(data=>{$('state-fields').textContent=data.state_fields.join(' · ');}).catch(()=>{$('state-fields').textContent='字段列表暂时无法加载。';});

$('model-select').onchange=()=>{revision++;if(lastResult)$('stale-result').hidden=false;health();};

async function downloadStatus(){if(!$('download-panel').open)return;try{const data=await api('/api/downloads');$('download-status').replaceChildren();for(const item of data.models){const row=document.createElement('p');const states={complete:'权重文件已就绪',running:'下载或校验中',pending:'等待下载',failed:'下载失败'};row.textContent=item.name+' · '+(states[item.state]||item.state);$('download-status').append(row);}}catch(e){$('download-status').textContent=e.message;}}
$('download-panel').ontoggle=downloadStatus;setInterval(downloadStatus,30000);

api('/api/models').then(data=>{if(data.models.some(m=>m.model_id==='qwen4b')){const option=document.createElement('option');option.value='qwen4b';option.textContent='Qwen3-VL-4B-Instruct（外部服务）';$('model-select').append(option);}}).catch(()=>{});
